version: "3.8"

services:
  fastapi_app:
    image: tramnguyenm/fastapi_app:latest
    ports:
      - "8000:8000"
    networks:
      - aqi_network
    environment:
      - PYTHONPATH=/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  streamlit_app:
    image: tramnguyenm/streamlit_app:latest
    ports:
      - "8501:8501"
    networks:
      - aqi_network
    environment:
      - API_URL=http://fastapi_app:8000
      - STREAMLIT_SERVER_ENABLE_WATCHER=false
      - STREAMLIT_SERVER_ENABLE_XSRF=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  aqi_network:
    driver: overlay
